services:
  api:
    build: .
    container_name: fastapi_grid_api
    environment:
      APP_DATABASE_URL: postgresql+psycopg://grid_user:grid_password@postgres:5432/grid_db
      APP_POSTGRESQL_DSN: postgresql+psycopg://grid_user:grid_password@postgres:5432/grid_db
      APP_SECRET_KEY: change-me-in-production
      APP_ACCESS_TOKEN_EXPIRE_MINUTES: 60
      APP_ALLOWED_ORIGINS: http://127.0.0.1:8001,http://localhost:8001
    ports:
      - "8010:8000"
    networks:
      - shared-net

networks:
  shared-net:
    external: true
